apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api_server
  namespace: default
  labels:
    app:  api_server
spec:
  selector:
    matchLabels:
      app: api_server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  api_server
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  api_server
        image:  MYAPP:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: monogo-secret
              key: url
        ports:
        - containerPort:  3000
          name:  api_server
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: api_server
  namespace: default
spec:
  selector:
    app: api_server
  type: LoadBalancer
  ports:
  - name: api_server
    port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 3000